### PR TITLE
Add docker pull suggestion for #5

### PR DESCRIPTION
**Pull request by sdd330**
The ServerUrl seems not returned by backend, can you take a look before merge?

### CODE REVIEW

**Comment by larrycai** [comment]
it reports error

    controllers/dockerregistryapi.go:230: config.ServerUrl undefined (type configuration has no field or method ServerUrl)

Code is not pushed complete

**Comment by larrycai** [comment]
Other comments for PR

1. better to use PIRATE_URL_ALIAS instead of SERVER_URL. And it is ok to keep SERVER_URL, then u help to update README.md to make it is complete PR
2. try to assign default value for this environment, like `<registry server>`, then we can see `docker pull <registry server>/library/helloworld` instead of `docker pull /library/helloworld`
3. will be good to have button "Copy to clipboard" like ;-)

Wait for new PR to merge

**Comment by sdd330** [comment]
I will change SERVER_URL to PIRATE_URL_ALIAS

**Comment by sdd330** [comment]
Updated

**Comment by larrycai** [comment]
@sdd330 thank, almost close to 0.2.0 release

**Pull request merged**
