### PR TITLE
Add tabs for image information

### PR DESCRIPTION
**Pull request by sdd330**

### CODE REVIEW

**Comment by tobegit3hub** [comment]
Looks good. Please have a review @larrycai :smiley:

**Comment by larrycai** [comment]
we discussed this f2f, and will design the homepage (based on images.html)
and image.html. they will follow the dockerhub.com and quay.io web UI, it
will be nice.

Meanwhile, we may generate the image spec for registry usage



On Mon, Jan 19, 2015 at 9:23 AM, tobe <notifications@github.com> wrote:

> Looks good. Please have a review @larrycai <https://github.com/larrycai> [image:
> :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobegit3hub/pirate/pull/21#issuecomment-70436384>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by larrycai** [comment]
and it worth merge now already.

**Comment by tobegit3hub** [comment]
Good job :+1:

**Comment by larrycai** [comment]
related with #18

**Pull request merged**
