### PR TITLE
Fix #4 remove multi-language support

### LINKED ISSUE #4: clean up the GUI to remove translation and seagull legacy codes
It seems there is no need to support multi-language since it is not for normal docker user.

Also the code base comes from seagull, will be nice to clean up

### PR DESCRIPTION
**Pull request by sdd330**
Some clean up

### CODE REVIEW

**Comment by larrycai** [comment]
@tobegit3hub do you agree with this ? it looks seagull is used for normal user as well, which demands multi-language support.

pirate's user is more for enterprise user, can we remove this feature first ? 

when we need, we bring it back in new way of translation (you mentioned once to redesign this)

is it ok ?

**Comment by tobegit3hub** [comment]
It's ok to me.

But I don't think we have to remove the code. We can simply use the normal string in html file and this is not contradictory.

**Comment by larrycai** [comment]
@sdd330 is it ok to keep the old translation if exists, and use normal string without translation for new string. thx.

**Comment by sdd330** [comment]
For bring old translation back, I suggest we keep it in backlog currently
It should be easy to bring it back base on the work done in seagull

**Comment by larrycai** [comment]
ok.

On Mon, Jan 12, 2015 at 4:47 PM, Yang Leijun <notifications@github.com>
wrote:

> For bring old translation back, I suggest we keep it in backlog currently
> It should be easy to bring it back base on the work done in seagull
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobegit3hub/pirate/pull/16#issuecomment-69541432>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by sdd330** [comment]
Multi-language support could be done using some server side technologies, keep it in one js will make the file very big, also hard to maintenance

**Pull request merged**
