### PR TITLE
Add docker service to make data request in one place

### PR DESCRIPTION
**Pull request by sdd330**
Some refactor and improvements

### CODE REVIEW

**Comment by larrycai** [comment]
thanks @sdd330 , it looks it solves the issue #11 as well (from my testing without digging into code, and I wait for your further testing to final close it)

**Comment by larrycai** [comment]
close #11

**Comment by larrycai** [comment]
@sdd330 can you add more information as @jackqt suggested.

**Comment by sdd330** [comment]
Sure, will consider them during code refactor

**Pull request merged**
